# Generated by Django 5.0.8 on 2024-09-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('key', models.CharField(max_length=140)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
