# Generated by Django 5.0.8 on 2024-09-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='courses',
            field=models.ManyToManyField(to='courses.course'),
        ),
    ]
