# Generated by Django 5.0.8 on 2024-09-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_video'),
        ('sites', '0002_alter_site_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
    ]
